# Command to start the FastAPI application using Uvicorn.
start-app:
    # Specify the full path for the main module if it's not in the current directory
    uvicorn main:app --reload

# Command to create a user. This command takes the user's name and password as parameters.
create-user name='your-user-here' password='your-password-here':
    curl -X POST "http://127.0.0.1:8000/create_user/" \
        -H "Content-Type: application/json" \
        -d "{\"name\": \"{{name}}\", \"password\": \"{{password}}\"}"

# Command to obtain a prediction. This command takes the user's name, password, and the text for sentiment analysis as parameters.
classify-text name='your-user-here' password='your-password-here' text='Your text here':
    curl -X POST "http://127.0.0.1:8000/prediction_with_auth/" \
        -H "Content-Type: application/json" \
        -H "name: {{name}}" -H "password: {{password}}" \
        -d "{\"text\": \"{{text}}\"}"

# Command to get the list of users
get-users:
    curl -X GET "http://127.0.0.1:8000/users"

# Command to get the list of texts for an authenticated user with user name and password as parameters.
get-texts name='your-user-here' password='your-password-here':
    curl -X GET "http://127.0.0.1:8000/texts" -H "name: {{name}}" -H "password: {{password}}"
