apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  selector:
    {{- toYaml .Values.backend.deployment.labels | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.deployment.container.port }}
  type: {{ .Values.backend.service.type }}
