apiVersion: v1 # Specifies the API version for Service resources.
kind: Service # Specifies that this is a Service resource.

metadata:
  name: {{ .Values.backend.service.name }} # Dynamically sets the service name from values.yaml.

spec:
  # Selector to match labels; converts to YAML and indents by 4 spaces.
  selector:
    {{- toYaml .Values.backend.deployment.labels | nindent 4 }}

  # Defines the ports and protocols for the service.
  ports:
    - protocol: TCP # Specifies the protocol (TCP). Hardcoded due to being a standard and widely applicable choice for most web-based applications.
      port: {{ .Values.backend.service.port }} # The service port that will be exposed.
      targetPort: {{ .Values.backend.deployment.container.port }} # The port on the container that the service should route to.

  type: {{ .Values.backend.service.type }} # Specifies the type of the service (ClusterIP).

##########
# {{ ... }}: Helm template expressions for dynamic value substitution.

# toYaml: Converts an object to YAML representation. Useful for converting complex selector labels into a readable format in Helm templates.

# | nindent N: Pipes toYaml output into nindent function, adding a newline and indenting the text by N spaces. 
# The - in {{- removes whitespace before the expression.

# .Values.path.to.value: Accesses values defined in the values.yaml file. The path navigates through the nested structure.
##########
